server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: 172.0.0.1:9092,172.0.0.1:9093,172.0.0.1:9094
    producer: # 生产者
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: default-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 500
    listener:
      ack-mode: manual_immediate #手动调用acknowledge()后立即提交，一般使用这种
